export const SEARCH_RESTAURANTS_REQUEST = 'SEARCH_RESTAURANTS_REQUEST';
export const SEARCH_RESTAURANTS_SUCCESS = 'SEARCH_RESTAURANTS_SUCCESS';
export const SEARCH_RESTAURANTS_FAILURE = 'SEARCH_RESTAURANTS_FAILURE';

export const GET_GEO_LOCATION_BY_COORDINATES_REQUEST = 'GET_GEO_LOCATION_BY_COORDINATES_REQUEST';
export const GET_GEO_LOCATION_BY_COORDINATES_SUCCESS = 'GET_GEO_LOCATION_BY_COORDINATES_SUCCESS';
export const GET_GEO_LOCATION_BY_COORDINATES_FAILURE = 'GET_GEO_LOCATION_BY_COORDINATES_FAILURE';

export const GET_GEO_LOCATION_BY_PLACE_NAME_REQUEST = 'GET_GEO_LOCATION_BY_PLACE_NAME_REQUEST';
export const GET_GEO_LOCATION_BY_PLACE_NAME_SUCCESS = 'GET_GEO_LOCATION_BY_PLACE_NAME_SUCCESS';
export const GET_GEO_LOCATION_BY_PLACE_NAME_FAILURE = 'GET_GEO_LOCATION_BY_PLACE_NAME_FAILURE';

export const GET_WEATHER_BY_COORDINATES_REQUEST = 'GET_WEATHER_BY_COORDINATES_REQUEST';
export const GET_WEATHER_BY_COORDINATES_SUCCESS = 'GET_WEATHER_BY_COORDINATES_SUCCESS';
export const GET_WEATHER_BY_COORDINATES_FAILURE = 'GET_WEATHER_BY_COORDINATES_FAILURE';

export const CLEAR_RESTAURANTS = 'CLEAR_RESTAURANTS';

export const SAVE_FAVORITE_TOUR = 'SAVE_FAVORITE_TOUR';
export const GET_FAVORITE_TOURS = 'GET_FAVORITE_TOURS';
export const REMOVE_FAVORITE_TOUR_BY_ID = 'REMOVE_FAVORITE_TOUR_BY_ID';
